component_depth: 1
languages:
- python
- name: perl
  production:
    include:
      - .*\.pl
      - .*\.pm
      - bin\.*
      - .*/db/.*\.pl
      - .*/lib/.*\.pm
      - .*/scanners/.*scan
    exclude:
      - bin\.*\.sh
  test:
    include:
      - .*/t/.*\.t
- name: javascript
  production:
    include:
      - .*/jmvc/seccubus/.*\.js
      - .*/jmvc/widgets/.*\.js
- script
exclude:
- .*/jmvc/.*
- .*/testdata/.*
- .*/tmp/.*
